ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/hx852xes/
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/
obj-$(CONFIG_TOUCHSCREEN_MTK_HIMAX_HX852xES) += himax_852xES.o himax_platform.o
